stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm start

deploy:
  stage: deploy
  script:
    - ssh ec2-user@3.239.61.7 'cd /group20/backend && git pull && npm install && pm2 restart index.js'
  only:
    - main
