stages:
  - build
  - deploy

build:
  stage: build
  script:
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - source "$NVM_DIR/nvm.sh"
    - nvm install --lts=fermium
    - npm install
    - npm start

deploy:
  stage: deploy
  script:
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - nvm install --lts=fermium
    - ssh ec2-user@3.239.61.7 'cd /group20/backend && git pull && npm install && pm2 restart index.js'
  only:
    - main